---
title: "Liste over dataset"
output: 
  html_document:
    toc: true
---

# Data

På denne side findes en liste over de datasæt, som har været benyttet i forbindelse med undervisningen på Statistisk Dataanalyse 1 (2019/20120).

## Data fra eksempler og opgaver i lærebogen

De fleste datasæt som benyttes i lærebogen findes i `isdals` R-pakken. 

Du kan læse mere om, hvordan du downloader og bruger data fra `isdals` R-pakken i [Opgave HS. 2](opgaver/hs1-4.pdf).

## Øvrige data

### Regneøvelser

Følgende datasæt har desuden været benyttet ved regneøvelserne

* Opgave HS.9: [johnson-fatpct.txt](data/johnson-fatpct.txt) - [johnson-fatpct.xlsx](data/johnson-fatpct.xlsx)
* Opgave HS.11+HS.15+HS.31: [punktplot2017.txt](data/punktplot2017.txt) - [punktplot2017.xlsx](data/punktplot2017.xlsx)
* Opgave HS.13: [sudoku-sd1.txt](data/sudoku-sd1.txt) - [sudoku-sd1.xlsx](data/sudoku-sd1.xlsx)
* Opgave HS.14: [stud2017-v2.xls](data/stud2017-v2.xls)
* Opgave HS.19: [mus_prop.txt](data/mus_prop.txt) - [mus_prop.xlsx](data/mus_prop.xlsx)
* Opgave HS.22: [fenoldata.txt](data/fenoldata.txt) - [fenoldata.xlsx](data/fenoldata.xlsx)
* Opgave HS.25: [aske-kalk2.txt](data/aske-kalk2.txt) - [aske-kalk2.xlsx](data/aske-kalk2.xlsx)
* Opgave HS.25: [aske-kalk2.txt](data/aske-kalk2.txt) - [aske-kalk2.xlsx](data/aske-kalk2.xlsx)
* Opgave HS.32: [lyskilde.txt](data/lyskilde.txt) - [lyskilde.xlsx](data/lyskilde.xlsx)
* Opgave HS.34: [patienter.txt](data/patienter.txt) - [patienter.xlsx](data/patienter.xlsx)

### Gamle eksamensopgaver

Følgende datasæt hører til de [gamle eksamensopgaver](https://github.com/anderstolver/StatData1_2019/tree/master/docs/eksamensopgaver).

Jeg minder om, at i eksamensopgaverne op til februar 2017 skulle man ikke selv køre R under eksamen. I stedet er der R kode i selve opgaven. Jeg har dog uploadet en del datasæt også til de gamle eksamensopgaver (før feb. 2017), og du opfordres til selv at køre R koden, hvis du bruger disse opgaver til eksamenstræning.

* Eksamen jan. 2019, opgave 1: [ss_gr.txt](data/ss_gr.txt) - [ss_gr.xlsx](data/ss_gr.xlsx)
* Eksamen jan. 2019, opgave 2: [florida.txt](data/florida.txt) - [florida.xlsx](data/florida.xlsx)
* Eksamen nov. 2018, opgave 1: [soeer.txt](data/soeer.txt) - [soeer.xlsx](data/soeer.xlsx)
* Eksamen nov. 2018, opgave 2: [elections.txt](data/elections.txt) - [elections.xlsx](data/elections.xlsx)
* Eksamen jan. 2018, opgave 1: [ss2017-18.txt](data/ss2017-18.txt) - [ss2017-18.xlsx](data/ss2017-18.xlsx)
* Eksamen jan. 2018, opgave 2:  [johnson-fatpct.txt](data/johnson-fatpct.txt) - [johnson-fatpct.xlsx](data/johnson-fatpct.xlsx)
* Eksamen nov. 2017, opgave 1: [guns.txt](data/guns.txt) - [guns.xlsx](data/guns.xlsx)
* Eksamen nov. 2017, opgave 3: [rodlaengde.txt](data/rodlaengde.txt) - [rodlaengde.xlsx](data/rodlaengde.xlsx)
* Eksamen feb. 2017, opgave 2: [sd12016-2.txt](data/sd12016-2.txt) - [sd12016-2.xls](data/sd12016-2.xls)
* Eksamen nov. 2016, opgave 1: [sd12016.txt](data/sd12016.txt) - [sd12016.xls](data/sd12016.xls)
* Eksamen nov. 2016, opgave 2: [aske-kalk.txt](data/aske-kalk.txt) - [aske-kalk.xlsx](data/aske-kalk.xlsx)
<!-- * Eksamen feb. 2016, opgave 2: [sleep.txt](data/sleep.txt) -->

* Eksamen nov. 2015, opgave 1: [mazdas.txt](data/mazdas.txt) - [mazdas.xlsx](data/mazdas.xlsx)
* Eksamen jan. 2015, opgave 1: [happy.txt](data/happy.txt) - [happy.xlsx](data/happy.xlsx)
* Eksamen jan. 2015, opgave 3: [foder.txt](data/foder.txt) - [foder.xlsx](data/foder.xlsx)
* Eksamen jan. 2014, opgave 1: [elefantgraes.txt](data/elefantgraes.txt) - [elefantgraes.xlsx](data/elefantgraes.xlsx)

### Forelæsninger

Følgende datasæt har desuden været benyttet ved forelæsningerne

* Eksempel fra 9/9-2019 (højder af studerende på StatData1 i 2017): [stud2017-v2.xls](data/stud2017-v2.xls)
* Data vedrørende månedlig indtægt fra studiejob indsamlet ved forelæsning d. 9/9-2019 fra studerende på StatData1 i 2019: [studiejob.xlsx](data/studiejob.xlsx)
* Eksempel fra 7/10-2019 (højder af studerende på StatData1 i 2017): [stud2017-v2.xls](data/stud2017-v2.xls)
* Data om studerende på Statistisk Dataanalyse 1 indsamlet ved forelæsning d. 2/9-2019: [sd1_eksperiment.xlsx](data/sd1_eksperiment.xlsx) (rådata) - [StatData1stud2019.txt](data/StatData1stud2019.txt) (rensede data)