---
title: "Generel info om Statistisk Dataanalyse 1 (version 2019/2020)"
output: 
  html_document:
    toc: true
---

***


Velkommen til kurset <h2>Statistisk Dataanalyse 1 (version 2019/2020)</h2>

De vigtigste oplysninger findes både på kursets Absalon-side og på kursets eksterne kursushjemmeside. Det er dog i høj grad kursushjemmesiden, som vil blive brugt til distribution af kursusmateriale.

Vær opmærksom på følgende vigtige links

* Kursets [officielle kursusbeskrivelse](https://kurser.ku.dk/course/lmab10069u/2019-2020)
* Kursets eksterne [hjemmeside](https://anderstolver.github.io/StatData1_2019/index.html)


***


# Praktiske oplysninger om undervisningen

## Kursusansvarlig og forelæser

Forelæsninger, kursusplanlægning og eksamen varetages af: Anders Tolver (<tolver@math.ku.dk>)


***


## Instruktorer

Der er tilknyttet 7 instruktorer (hjælpelærere) til kurset

* Hold 6: Asger Andersen
* Hold 5: Frederik Mølkjær Andersen
* Hold 2: Jens Baalkilde Andersen
* Hold 3: Frederik Baadsgaard
* Hold 1: Josva Engmose Jensen
* Hold 4: Mark Bech Knudsen
* Hold 7: Mathias Petersen


***


## Skema

Der er planlagt 5 forelæsninger og 5 øvelsestimer hver uge

* Mandag: forelæsninger 13:00-14:45, øvelser 15:00-16:45
* Onsdag: forelæsninger 9:00-10:45+15:00-15:45, øvelser 11:00-11:45+13:00-14:45

**Der kan forekomme mindre afvigelser fra planen, men jeg skal sørge for at annocere dette i god tid.**

I kursusuge 8 er der kun undervisning mandag (men altså ikke onsdag).

For en præcis oversigt over lokaler henvises til [den officielle skemaside for KU](https://skema.ku.dk/tt/tt.asp?SDB=KU1920&language=DK&folder=Reporting&style=textspreadsheet&type=module&idtype=id&id=89738&weeks=6&days=1-5&periods=1-68&width=0&height=0&template=SWSCUST2+module+textspreadsheet). Bemærk, at linket viser lokaleoversigten for kursusuge 1. Du kan ikke være sikker på, at du skal være i samme lokale hver uge!

Du kan se skemaet for de følgende uger ved at klikke på linket `Næste uges skema >` nederst på den side, som jeg har linket til.


***


## Plan over kursusaktiviteter

For en detaljeret plan over kursusaktiviteter henvises til følgende [kursusplan](https://anderstolver.github.io/StatData1_2019/kursusplan.html).

Detaljerne i kursusplanen for den kommende uge annonceres som udgangspunkt torsdag eftermiddag. Jeg vurderer løbende hvordan kurset skrider frem , og det er derfor ikke muligt at lave en detaljeret plan for hele kurset fra starten. Der kommer en grov foreløbig oversigt over kurset omkring blokstart.


***


## Indhold

Der henvises igen til kursus eksterne hjemmeside og til den officielle kursusbeskrivelse for mere information.

Vigtige emner på kurset er

* Statistiske grundbegreber: Sandsynligheder, variation, statistisk model, estimation, test, konfidensintervaller
* Analyser baseret på normalfordelingen: Sammenligning af stikprøver, en- og tosidet variansanalyse, regressionsanalyse
* Analyser af diskrete data: Binomialfordelingen, tosidede antalstabeller

Der lægges vægt på "oversættelse" fra biologiske problemstillinger til statistisk formulering og analyse, samt på fortolkning af resultaterne.

Beregninger gennemføres i simple tilfælde med lommeregner, men som hovedregel ved brug af det statistiske program R - også ved eksamen.


***


## Forudsætninger

Kurset forudsætter kurset Matematik og databehandling eller lignende. Specifkt forudsættes kendskab til R, således at vi ikke starter forfra med R. Hvis din baggrund er anderledes således at du ikke kender R, må du insdstille dig på ekstra arbejde i starten af kurset. 


***


## Feedback

Hvis der er problemer i løbet af kurset, så sig til i løbet af kurset i stedet for at vente til evalueringen. Forhåbentlig kan vi så løse problemerne mens kurset kører.


***


# Om undervisningen

## Undervisningsmateriale

Vi benytter os af lærebogen 

* Claus Thorn Ekstrøm & Helle Sørensen: **Statistical Data Analyse for the Life Sciences (Second Edition)**

Det gennemgåede pensum dækkes i grove træk af indholdet kapitel 1-7, dele af kapitel 8, kapitel 10-12 og kapitel 14. En mere detaljeret pensumliste laves løbende som kurset skrider frem.

 til brug ved læsning af lærebogen (kom gerne med flere forslag).

Du vil i lige så høj grad komme til at opleve, at vi trækker på følgende undervisningsmateriale

* forelæsningsslides
* opgaver og opgaveløsninger
* R programmer


***


## Forelæsninger

Forelæsningerne bliver ikke en slavisk gennemgang af stoffet i bogen. Jeg vil i stedet forsøge at fokusere på ideer, fortolkninger, praksis og forståelse.

Der vil være derfor være mange ting i bogen, der ikke bliver gennemgået. Det betyder ikke at de ikke er vigtige, og I forventes at læse dem selv derhjemme. I er altid velkomne til at stille spørgsmål til dem. 

Ved forelæsningerne benyttes forelæsningsslides der gøres tilgængelige umiddelbart før forelæsningen.


***


## Øvelsestimer

Ved øvelsestimerne sidder I og regner de opgaver der er annonceret på ugeplanen. Der er instruktorer der kan hjælpe jer, og I er velkomne til at spørge om alt hvad der har med kurset at gøre. Enkelte opgaver vil blive gennemgået ved tavlen.

Der vil ikke være tid til at regne alle opgaver i løbet af øvelsestimerne, og de vil ikke alle blive gennemgået. Resten er hjemmearbejde, og det er dit eget ansvar at få fulgt op på opgaverne. 


***


## Afleveringsopgaver

Der vil blive stillet en afleveringsopgave et par gange i løbet af kurset. Det er frivilligt at aflevere, men det er et rasende godt tilbud og en fremragende mulighed for at få feedback på din skriftlige fremstilling af besvarelsen.


***


## Hjemmearbejde

Udover de skemalagte timer skal du naturligvis arbejde intensivt med stoffet på egen hånd. Undervisningen (skal) tilrettelægges, så et fuldtidsstudie kræver, at du bruger mindst 40 timer om ugen på dit studie (heraf mindst 20 timer på Statistik Dataanalyse). Hvis du bruger mindre end 20 timer om uger, så kan du ikke forvente at få et fornuftigt udbytte af kurset, og din præstation ved eksamen vil være dårligere, end den behøvede at være. Det er naturligvis meget forskelligt fra person til person hvordan denne tid bedst fordeles på de forskellige kursuselementer, men et løst forslag er følgende:

* Forelæsninger: 5 timer
* Øvelsestimer: 5 timer
* Læse i bogen før og efter forelæsninger: 4 timer
* Selvstændigt arbejde med opgaver, slides, R programmer m.m. (før/efter timer): 6 timer


***


## R programmer og datasæt

Det er et vigtigt element i undervisningen, at du selv lærer at bruge det statistiske program R til at lave statistiske beregninger.

R og RStudio vil blive benyttet på kurset, dels til egentlig datanalyse og dels til små simulationsstudier. R er et statistikprogram, RStudio er en brugergrænseflade som gør arbejdet med R (endnu) mere behageligt. 

Sørg for at have installeret de nyeste versioner af R og RStudio på din computer ved kursusstart og hav din laptop med til øvelserne. Der er en lang række hyppige problemer som lettest løses ved at opdatere R og RStudio til nyeste versioner, så lad være med at falde for fristelsen og køre med (old)gamle versioner.

Links til installation:

Du skal først installere R: [www.r-project.org/](http://www.r-project.org/) 

* klik CRAN i venstre bjælke og vælg et mirror i Danmark
* vælg operativsystem
* følg vejledningen (brug defaultindstillingerne)

Dernæst skal du installere RStudio: [www.rstudio.com](http://www.rstudio.com/)

* Vælg "RStudio Desktop" (gratis)

Hvis du allerede har RStudio installeret, så kan programmet også updateres inde fra RStudio 

* vælg `Help` i menuen og derefter `Check for updates`

Jeg vil selv bruge filformatet `R Markdown` i løbet af kurset. Det er et format, hvor man nemt kan integrere (dvs. kombinere) R-kode, R-output, grafer og almindelig tekst, og få resultatet vist som pdf, html eller MS Word. Jeg vil opfordre jer kraftigt til selv at vænne jer til at benytte dette format. Jeg viser hvordan man gør i kursusuge 1, og alle mine R programmer vil være skrevet i dette format.


I forbindelse med forelæsninger, øvelser og eksamen vil i skulle indlæse og regne på et større antal datasæt. 
 
Alle datasæt, som optræder i lærebogen kan downloades ved at installere R-pakken `isdals` fra CRAN.

Øvrige datasæt vil blive uploaded til en særlig folder på [kursets eksterne hjemmeside](https://anderstolver.github.io/StatData1_2019/index.html).


***


# Eksamen

Der afholdes en 4 timer skriftlig eksamen, som ifølge mine oplysninger ligger d. 6. november 2019 (men check selv når tiden nærmer sig!). 

Alle hjælpemidler tilladt inklusive brug af R på egen medbragte computer. Du skal have en computer med til eksamen som har R installeret da dele af opgaven ikke kan løses uden brug af R. Datasæt vil blive udleveret på en USB-stick til eksamen, så du skal anskaffe en adapter hvis du ikke har en USB-indgang i din computer. Dette betyder også, at I må aflevere jeres besvarelse på computer. 

Man kan aflevere håndskrevet på papir, elektronisk som pdf-fil på USB-stick, eller en blanding. Vi snakker om, hvordan [R Markdown](https://rmarkdown.rstudio.com) formatet kan være hensigtsmæssigt her, og inddrager dette intensivt i undervisningen. 

To vigtige ting

* Man selv skal køre R ved eksamen. Til og med 2016 var den nødvendige kode og output givet i opgaven, så ældre eksamenssæt ikke er helt repræsentative for nye sæt, men problemstillinger og spørgsmål vil være af samme type.
* En mindre del af eksamenssættet vil bestå af quizspørgsmål (*multiple choice*). Vi vil træne dette vha. små quizzer undervejs i undervisningsforløbet.

Det er jeres eget ansvar at holde jer orienteret om

* frister for til- og afmelding til eksamen (jeg hverken må eller kan hjælpe)
* tid og sted for den skriftlige eksamen

## Notat med info og gode råd om eksamen

Supplerende info og gode råd om eksamen findes i følgende [notat om eksamen](notater/om-eksamen.pdf).

## Reeksamen

Hermed følger lidt information til de studerende, som skal til reeksamen i Statistisk Dataanalyse 1 i januar 2020.

Det er Studieadministrationen som planlægger eksamendatoerne, men det kan være nyttigt at kende følgende [link til eksamens- og reeksamensdatoer](
https://www.science.ku.dk/uddannelser/eksamensdatoer/). Se under Blok 1 og find kurset Statistisk Dataanalyse 1.

Pensum til reeksamen er identisk med pensum til den ordinære eksamen og kan bl.a. findes i følgende [notat om eksamen](notater/om-eksamen.pdf).

Udgangspunktet bør være, at man ikke skal forvente at kunne løse alle opgaver til reeksamen med mindre man har styr på hele pensum. Det kan være en uoverskuelig opgave at få alt læst op helt alene, så her er et par supplerende råd/tilbud, som kan gøre det lettere at komme igennem reeksamen.

* Jens Baalkilde Andersen (øvelseslærer fra blok 1) er blevet hyret til at afholde 2 øvelsessessioner/spørgetimer (hver af 2 x 45 minutters varighed) op imod reeksamen. Jeg tænker, at formatet vil være, at Jens gennemgår opgaverne, og at I stiller opklarende spørgsmål.

    + **Onsdag d. 22/1-2020 fra kl. 13:00-14:45 i lokale A1-34.21 på Thorvaldsensvej 57**: Gennemgang af opgave 1+2  fra eksamen i januar 2019 (link: [gamle eksamensopgaver](https://github.com/anderstolver/StatData1_2019/tree/master/docs/eksamensopgaver) + [data](data.html)). Gennemgang af opgave HS 29 + HS 30.
    + **Mandag d. 27/1-2020 i lokale [opdateres senere] **: Gennemgang af eksamenssættet fra den ordinære eksamen d. 6/11-2019. Link til opgaven finder under [gamle eksamensopgaver](https://github.com/anderstolver/StatData1_2019/tree/master/docs/eksamensopgaver), og her er data til opgave 1: [hunde.txt](data/hunde.txt) - [hunde.xlsx](data/hunde.xlsx) samt data til opgave 2: [training.txt](data/training.txt) - [training.xlsx](data/training.xlsx)
    

* I næste uge (20.-24. januar) vil jeg dagligt checke diskussionsforum i Absalon, hvor jeg vil forsøge at besvare jeres spørgsmål, som måtte opstå i forbindelse med eksamenslæsningen. Jeg er på ferie i reeksamensugen (27.-31. januar), hvorfor jeg ikke vil besvare beskeder/emails i de sidste dage op til reeksamen. Bemærk dog, at den sidste øvelsesssion ved Jens afholdes så tæt på reeksamen , så I har mulighed for at få lidt hjælp helt op til d. 27/1.

* Nedenfor vil jeg lave en komprimeret liste over ting, som du kunne vælge at fokusere på fra de forskellige undervisningsuger i forbindelse med oplæsning til reeksamen. Der henvises til i øvrigt til detaljerne i kursusplanen for de enkelte undervisningsuger (samt til det øvrige materiale på kursushjemmesiden).

    + Vigtige emner fra **kursusuge 1+2** er: i) hvordan checker man om data er normalfordelte, ii) hvordan analyserer man en normalfordelt stikprøve (enstikprøveproblemet) herunder estimation og konfidensinterval for middelværdien for en stikprøve. Jeg tænker at opgaverne 4.5 (fra lærebogen) samt HS 8, HS 10 kunne være et godt sted at starte. Desuden findes der i eksamensopgaverne (fra november 2018 og frem) flere multiple choice spørgsmål som vedr. konfidensintervaller for en stikprøve.
    
    + På baggrund af materialet i **kursusugerne 1-3** bør du have styr på ensidet variansanalyse og lineær regresssion. Med henvisning til oversigten på slide 3 fra 16/9-2019 og modeloversigten på slide 7 bør du: i) have styr på hvornår modellerne er relevante, ii) kunne opskrive den tilhørende statistiske model på papir, iii) kunne fitte/estimere modellerne i R, iv) kunne udtrække/fortolke estimater, standard errors og konfidensinterveller for parametrene i modellen på baggrund af R udskrifterne. Du bør desuden kunne teste om hældningsparameteren i en lineær regressionsmodel er 0, og du bør kunne teste om middelværdien er ens i to eller flere grupper for en ensidet variansanalysemodel. Hvis du læser og forstår kommentarerne i de meget grundige R-programmer fra 16/9-2019 og 18/9-2019, så er du nogenlunde dækket ind. Diskussionen om to stikprøver (parrede og uparrede fra Afsnit 3.5 og 5.4) dækkes af undervisningen i uge 3, og voldte en del problemer for studerende til den ordinære eksamen (dvs. delopgave 2.1+2.2 fra eksamen i november 2019). Regn desuden opgave 1 fra eksamen i november 2018.
    
    + I **kursusuge 4** diskuterede vi bl.a. hvordan man generelt kan bruge F-test til at sammenligne en stor model (*full model*) med en reduceret model (*nul model*), hvor man har lagt restriktioner på nogle af parametrene (til beskrivelse af middelværdistrukturen). Et hovedeksempel handler om, hvordan man sammenligner middelværdien for to eller flere grupper i en ensidet ANOVA. Desuden snakkede vi i denne uge om forskellen på konfidensintervaller og prædiktionsintervaller samt om modelkontrol (mere generelt). Slides samt R program fra 25/9-2019 giver et nogenlunde overblik, og opgave 1 fra eksamen i november 2018 kommer godt rundt omkring emnerne fra uge 1-4 i forbindelse med den ensidede ANOVA.
    
    + I **kursusuge 5** snakkede vi om multiple lineær regression. Du kan fx. regne opgave 2 fra eksamen i november 2018. Desuden repeterede vi lineær regression og ensidet ANOVA i denne uge. Teknikken med at anskue den lineære regressionsmodel som restriktion af enten en ensidet ANOVA eller en kvadratisk regressionsmodel er nyttig. Dette er indgående diskuteret i R-programmet fra 30/9-2019. Opgave HS 22 kommer også godt rundt i denne problemstilling.
    + I **kursusuge 6** så vi især på to typer af modeller, hvor man modellerer sammenhængen mellem en kontinuert respons og to forklarende variable. Hvis begge forklarende variable er kategoriske taler vi om tosidet variansanalyse (ANOVA), og hvis der er både kontinuerte og kategoriske variable taler vi om en blandet model. Du skal kunne forstå og fortolke R-output fra tosidet ANOVA både med og uden vekselvirkning. Du kan med fordel løse opgave 1 fra eksamen 2019 for at blive fortrolig med tosidet ANOVA. R-programmet fra 7/10-2019 gør et stort nummer ud af at forklare, hvordan man kan fortolke outputtet fra de forskellige tosidede variansanalysemodeller. De blandede modeller diskuteres i R-programmet fra 9/10-2019 vedr. løbetider på DHL-stafetten og i opgave 2 fra eksamen i november 2019 (ordinære eksamen!).
    
    + I **kursusuge 7** snakkede vi om forskellige modeller for analyse af antalstabeller. Det er essentielt at forstå, hvordan man udregner sandsynligheder i en binomialfordeling (klassisk quiz-spørgmål i multiple choice opgaver). Desuden snakkede vi om, hvordan man i) estimerer og beregner konfidensintervaller for en andel (dvs. antal / total), ii) tester hypoteser om at andelen har en bestemt værdi (fx. 0.5), iii) sammenligner to binomialfordelinger, iv) laver test for homogenitet og test for uafhængighed baseret på antalstabeller. Der er mange emner og næppe nogen vej uden om at nærstudere slides og R-programmer fra denne uge, hvis du gerne vil være ordentlig forberedt. Husk især at øve på quiz-spørgsmål fra eksamen og quizzer i Absalon, som vedrører denne del af pensum.

* Husk at en del af eksamen består af quiz-spørgsmål. Alle de 7 quizzer som vi diskuterede under afviklingen af kurset i blok 1 er stadig tilgængelige via Absalon. Alternativt (og måske bedre) kan du starte med at lave quiz-spørgsmål fra de sidste 3 eksamenssæt (fra november 2018 og fremefter).    
    