---
title: "Kursusplan"
output: 
  html_document:
    toc: true
---

# Oversigt over undervisningen

Skemaet giver en grov foreløbig plan for undervisningen. Planen og linket (til højre for hver kursusdag) med detaljerede oplysninger opdateres løbende for hver enkelt undervisningsgang.

Kursusuge | Dag | Emner | Lærebog | Detaljer 
----------| --- | ----- | ------- | -------- 
1 | Mandag (2/9) | Introduktion, R, Deskriptiv statistik | Ch. 1 | [link](#uge1)
1 | Onsdag (4/9) | Intro til lineær regression og ensidet ANOVA | Ch. 2-3 | [link](#uge1) 
2 | Mandag (9/9) | Normalfordelingen  | Ch. 4.1+4.3 | [link](#uge2) 
2 | Onsdag (11/9) | Analyse af en stikprøve | Ch. 4.2+4.4, Ch. 5.3.1-5.3.3 | [link](#uge2)   
3 | Mandag (16/9) | Linæer regression og ensidet ANOVA (i detaljer) | Ch. 5.1-5.2 | [link](#uge3) 
3 | Onsdag (18/9) | Hypotesetest med fokus på t-test | Resten af Ch. 5, Ch. 3.5, (Ch. 6.1-6.2) | [link](#uge3)   
4 | Mandag (23/9) | F-test samt diskussion af fejltyper ved statistiske test | (Ch. 6.1-6.2) + Ch. 6.3+6.4 | [link](#uge4)  
4 | Onsdag (25/9) | Modelkontrol og prædiktion | Ch. 7 | [link](#uge4)   
5 | Mandag (30/9) | Repetition / Opsummering | Intet nyt! (Ch. 1-7) | [link](#uge5) 
5 | Onsdag (2/10) | Multiple lineær regression | Ch. 8.1 | [link](#uge5)  
6 | Mandag (7/10) | Tosidet ANOVA | Ch. 8.2 | [link](#uge6) 
6 | Onsdag (9/10) | Modeller med både kvantitative og kontinuerte forklarende variable | Ch. 8.3 | [link](#uge6)  
7 | Mandag (21/10) | Binomialfordelingen  | Ch. 11 | [link](#uge7) 
7 | Onsdag (23/10) | Analyse af antalstabeller | Dele af Ch. 12 | [link](#uge7)  
8 | Mandag (28/10) | Repetition / opgavegennemgang | Intet nyt! | link  

## Liste over gennemgået pensum

Følgende afsnit fra lærebogen er gennemgået i kursusuge 1-7

* Chapter 1: Datatyper, visualisering og deskriptiv statistik

* Chapter 2: Introduktion til lineær regression

* Chapter 3: Sammenligning af grupper og introduktion til ensidet variansanalyse.

* Chapter 4: Normalfordelingen. Nogle af de mere teoretiske ting omkring Infobox 4.2, 4.3 og 4.5 illustreres primært gennem eksempler (computersimulationer). Afsnit 4.4. er kun kursorisk. 

* Chapter 5.3.1-5.3.3: Konfidensintervaller med fokus på konstruktion af konfidensintervaller for middelværdien i en sample (*one sample problem*)

* Chapter 5.1-5.2: Generelle statistisk begreber (statistisk model, estimation) med fokus på lineær regression og ensidet ANOVA.

* Chapter 6.1-6.2: Hypotesetest med særlig fokus på t-test.

* Chapter 6.3-6.4: Om F-test med udgangspunkt i sammensatte hypoteser (flere grupper på en gang) i ensidet ANOVA

* Chapter 6.5: Om fejl af type I og II i forbindelse med hypotesetest

* Chapter 7: Modelkontrol og prædiktion i forbindelse med modeller fittet med `lm()` funktionen i R

* Chapter 8.1: Multipel lineær regression

* Chapter 8.2, 8.3, 8.4.1, 8.4.2: Om tosidet ANOVA og blandede modeller (både kontinuerte og kategoriske forklarende variable). Afsnittene 8.2.2 og 8.4.3 er ikke pensum.

* Chapter 11: Om binomialfordelingen
* Chapter 12: Om analyse af antalstabeller (dog ikke afsnit 12.2.3 og 12.2.4)

# Program for enkelte uger


***


## Kursusuge 1 {#uge1}

### Generel info

Ud over at følge undervisningen bør du i kursusuge 1

* læse den [praktiske information om kurset](https://anderstolver.github.io/StatData1_2019/index.html)

* installere de nyeste versioner af [R](https://cran.r-project.org) og [R Studio](https://www.rstudio.com/products/rstudio/download/) på din computer

* anskaffe dig et eksemplar af lærebogen *Claus Thorn Ekstrøm & Helle Sørensen:* **Statistical Data Analyse for the Life Sciences (Second Edition)**

Bemærk desuden, at der sikkert er stillet flere opgaver end du kan nå i timerne, og at du skal lave resten derhjemme. Husk at du forventes at arbejde 20 timer om ugen med kurset, for at få fuldt udbytte af undervisningen.

### Forelæsninger

#### Forelæsninger mandag kl 13.00-14.45 i aud - A2-82.01 (3-02)

Emner

* Introduktion til kurset
* Genopfriskning af R
* Kapitel 1: Datatyper, deskriptiv statistik

Slides til dagens forelæsning: [fuld version](slides/sd1_forel190902.pdf) - [kort version: 4 slides per side](slides/sd1_forel190902_short.pdf)

R-program fra forelæsning d. 2/9-2019: [output](R/forel190902_Rprog.html) - [R Markdown](R/forel190902_Rprog.Rmd)

#### Forelæsninger onsdag kl. 9.00-10.45 i aud - A2-82.01 (3-02) og kl. 15.00-15.45 i aud - A2-82.01 (3-02)

Jeg vil bruge mindre energi på de matematiske detaljer end der er lagt op til i bogen. Det vigtigste er at forstå problemstillingerne, princippet om mindste kvadraters metode, samt begreber som variation, forventede værdier, population, stikprøve. 

* Kapitel 2: Intro til lineær regression og korrelation
* Kapitel 3, dog ikke detaljerne i afsnit 3.4: Intro til ensidet ANOVA
* R Markdown. R Markdown er et filformat til at generere dokumenter der både indeholder almindelig tekst og R-kode med tilhørende output. Det er en hensigtsmæssig måde at arbejde på. Jeg bruger det selv i forbindelse med forelæsningerne, og opgave HS.5 i næste uge hjælper dig i gang.

Slides til dagens forelæsning: [fuld version](slides/sd1_forel190904_handout.pdf) - [kort version: 4 slides per side](slides/sd1_forel190904_short.pdf)

R-program fra forelæsning d. 4/9-2019: [output](R/forel190904_Rprog.html) - [R Markdown](R/forel190904_Rprog.Rmd)


### Øvelsestimer

#### Øvelser mandag kl. 15.00-16.45 (se lokaleplanen)

HS-opgaver kan findes [her](https://github.com/anderstolver/StatData1_2019/tree/master/docs/opgaver). De øvrige opgaver er fra lærebogen.

* Opgave HS.1: Om at arbejde med R og RStudio. Hvis du har helt styr på hvordan du gebærder dig i R, kan du springe opgaven over.
* Opgave 1.1: Datatyper
* Opgave 1.2: Summary measures. Kommentarer: (a) Du må gerne bruge R, men vær sikker på at du forstår hvad der foregår! (b) Se sidste spørgsmål i HS.1 for hvordan du kan indlæse data til R. (c) Man kan tænke på første kvartil som medianen i deldatasættet der inkluderer observationerne fra den mindste observation til medianen.
* Opgave 1.9. Summary measures, fortsættelse af opgave 1.2
* Opgave 1.7, men kun spørgsmål 1-4: Histogram og boxplot i R
* Opgave 1.8: Histogrammer og boxplots

#### Øvelser onsdag kl. 11:00-11:45 og kl. 13.00-14.45 (se lokaleplanen)

HS-opgaver kan findes [her](https://github.com/anderstolver/StatData1_2019/tree/master/docs/opgaver). De øvrige opgaver er fra lærebogen.

* Opgave HS.2: Om installation af R-pakker, datasæt fra pakker
* Opgave HS.3: Om datasæt og variable i R
* Opgave 2.3, men kun spørgsmål 1-7: Lineær regression og korrelation
* Opgave 2.7: Korrelation 
* Opgave HS.4: Ensidet ANOVA
* Opgave 3.1: Ensidet ANOVA


***


## Kursusuge 2 {#uge2}

### Generel info

* Jeg fik stillet lidt for få opgaver i sidste uge (særligt til onsdagstimerne), så jeg har skruet lidt op for mængden i denne uge. Husk at lave de opgaver hjemme som du ikke når i timerne.

* Jeg har aftalt med instruktorerne, at der lægges vejledende besvarelser ud i Absalon kort tid efter øvelsestimerne (**NB: ikke på den eksterne kursushjemmeside!**). Det er instruktorerne som på skift får ansvaret for at lægge opgaverne ud, så I bedes henvende jer til instruktorerne, hvis I har spørgsmål til besvarelserne. Brug besvarelserne med omhu, dvs. til at checke dine resultater eller hvis du har tænkt længe, men er gået i stå. Du bliver ikke i stand til at regne nye opgaver ved blot at kigge besvarelserne igennem.

* Opgave HS.9 (til onsdagsøvelserne) handler om indlæsning af data fra eksterne filer. Der vil være opgaver til eksamen som overhovedet ikke kan løses hvis man ikke kan læse data ind, så sørg for at få styr på det med det samme.

### Forelæsninger

#### Forelæsninger mandag kl 13.00-14.45 i aud - A2-82.01 (3-02)

Ved dagens forelæsning snakker vi om lærebogens Kapitel 4, dog ikke afsnit 4.2 og 4.4. Hovedemnerne er

* Normalfordelingen og dens egenskaber
* Hvordan checker man om data er normalfordelte?
* Hvorfor er normalfordelingen så vigtig?

Slides til dagens forelæsning: [fuld version](slides/sd1_forel190909_handout.pdf) - [kort version: 4 slides per side](slides/sd1_forel190909_short.pdf)

R-program fra forelæsning d. 9/9-2019: [output](R/forel190909_Rprog.html) - [R Markdown](R/forel190909_Rprog.Rmd)

#### Forelæsninger onsdag kl. 9.00-10.45 i aud - A2-82.01 (3-02) og kl. 15.00-15.45 i aud - A2-82.01 (3-02)

Kapitel 5 tages i en lidt speciel rækkefølge, idet vi først snakker om model, estimation og konfidensinterval for en enkelt stikprøve (one sample), og først senere går tilbage til lineær regression og ensidet ANOVA. I bogen er de tre modeltyper blandet mere sammen. 

* Afsnit 4.2: Analyse af en stikprøve (one sample)
* Afsnit 4.4: Du kan læse dette overfladisk; jeg siger nok lidt om det ved forelæsningerne
* Afsnit 5.3: Indtil delafsnit 5.3.4 (dvs. side 117 nederst til side 124 øverst)
* Eftermiddag: Om gæt på antal punkter; samme data som opgave HS.11
* Eftermiddag: Vi vil kort diskutere den Quiz til Kursusuge 1 som er tilgængelig i Absalon (under Quizzes).

Slides til dagens forelæsning: [fuld version](slides/sd1_forel190911_handout.pdf) - [kort version: 4 slides per side](slides/sd1_forel190911_short.pdf)

R-program fra forelæsning d. 11/9-2019: [output](R/forel190911_Rprog.html) - [R Markdown](R/forel190911_Rprog.Rmd)

### Øvelsestimer

#### Øvelser mandag kl. 15.00-16.45 (se lokaleplanen)

HS-opgaver kan findes [her](https://github.com/anderstolver/StatData1_2019/tree/master/docs/opgaver). De øvrige opgaver er fra lærebogen.

* Opgave HS.5: Om R Markdown. Hvis du har tænkt dig at lave eksamensbesvarelsen på computeren, så kan du med fordel bruge R Markdown.
* Opgave 4.1: Histogrammer og stikprøvestørrelser.
* Opgave HS.6: Normalfordelingen
* Opgave HS.7: Transformation
* Caseopgave 1, del I: side 428 i bogen

#### Øvelser onsdag kl. 11:00-11:45 og kl. 13.00-14.45 (se lokaleplanen)

HS-opgaver kan findes [her](https://github.com/anderstolver/StatData1_2019/tree/master/docs/opgaver). De øvrige opgaver er fra lærebogen.

* Opgave HS.9: Indlæsning af data.
* Opgave HS.10: Konfidensinterval på flere måder i R
* HS.8: Konfidensinterval
* Opgave HS.11: Gæt på antal punkter, variationskoefficient. 
* Opgave 4.5: Evaluering af QQ-plots
* HS.12: Ekstra spørgsmål til opgave 4.5 

***


## Kursusuge 3 {#uge3}

### Generel info

* Ved den skriftlige eksamen vil en del af eksamenssættet bestå af *multiple choice opgaver* (dvs. små quiz-spørgmål). For at give dig mulighed for at træne dette format, så vil der hver uge være en ny quiz i Absalon, som du kan øve dig på. Disse quizzer gøres typisk tilgængelige onsdag eftermiddag eller torsdag (dvs. efter den skemalagte undervisning), så du kan passende bruge noget at dit hjemmearbejde til at lave quizzerne, og dermed repetere ugens pensum.

* I denne uge skal vi have udvidet vores diskussion af statistiske modeller, estimation, standard errors og konfidensintervaller til også at dække lineær regression og ensidet variansanalyse. Derudover skal vi snakke om hypotesetest. Nogle af jer vil opleve at analyserne hver for sig er nogenlunde nemme at gå til, og at det svære først og fremmest er at finde ud af hvilken analyse der er den korrekte at gribe fat i. Jeg anbefaler at I bruger [modelvalgsdiagrammet](notater/modeller.pdf) (flowdiagram/procesdiagram), som jeg tit viser til forelæsningerne.

* Du formodes nu (efter kursusuge 2) at være i stand til at læse data ind fra excel- eller tekstfiler ([opgave HS.9](opgaver/hs5-12.pdf)). Indlæsning af xlsx-filer kræver pakken readxl. Den kan installeres en gang for alle som forklaret i opgave HS.9, men skal loades når du skal bruge den, fx vha. library-funktionen.

* Husk at rækkefølgen af opgaver ikke er tilfældig, så jeg anbefaler at du regner dem i den rækkefølge de står på ugeplanen.

### Forelæsninger

#### Forelæsninger mandag kl 13.00-14.45 i aud - A2-82.01 (3-02)

I onsdags snakkede vi om statistisk model, estimation, standard error, konfidensinterval for en enkelt stikprøve. I dag skal vi have de samme begreber på plads for ensidet ANOVA og lineær regression.

* Kapitel 5. Bemærk at vi allerede har snakket om det meste af afsnit 5.3, og at vi nok ikke når afsnit 5.4 i dag.

Slides til dagens forelæsning: [fuld version](slides/sd1_forel190916_handout.pdf) - [kort version: 4 slides per side](slides/sd1_forel190916_short.pdf)

R-program fra forelæsning d. 16/9-2019: [output](R/forel190916_Rprog.html) - [R Markdown](R/forel190916_Rprog.Rmd)

#### Forelæsninger onsdag kl. 9.00-10.45 i aud - A2-82.01 (3-02) og kl. 15.00-15.45 i aud - A2-82.01 (3-02)

Vi starter med at gennemgå s. 27-34 fra forelæsningsslides til mandagsforelæsningen (16/9-2019) i et roligt tempo!

Dernæst gennemgår vi

* Afsnit 3.5 og 5.4 om to stikprøver (parrede og uparrede)
* Afsnit 6.1-6.2 om hypotesetest (i det omfang tiden tillader det)
* Eftermiddag: Fortsat analyse af data om punktplot, denne gang med fokus på sammenligning af mænd og kvinder og fortolkning af estimater efter transformation.

Ved forelæsningen onsdag eftermiddag bruger vi desuden ca. 20 minutter på at gennemgå quizzen hørende til kursusuge 2 (som findes i Absalon). I forventes at have lavet quizzen hjemme inden onsdagsforelæsningen, og vi *spilder* ikke dine medstuderendes tid med at afsætte undervisningstid til, at du kan lave quizzen.

Slides til dagens forelæsning: [fuld version](slides/sd1_forel190918_handout.pdf) - [kort version: 4 slides per side](slides/sd1_forel190918_short.pdf)

R-program fra morgenforelæsning d. 18/9-2019: [output](R/forel190918_Rprog.html) - [R Markdown](R/forel190918_Rprog.Rmd)

R-program fra eftermiddagsforelæsning d. 18/9-2019: [output](R/punktplot190918_Rprog.html) - [R Markdown](R/punktplot190918_Rprog.Rmd)

### Øvelsestimer

#### Øvelser mandag kl. 15.00-16.45 (se lokaleplanen)

Der er opgaver i flere modeltyper. Brug gerne modeldiagrammet i hver opgave til at gennemskue hvilket set-up der er det relevante.

* Opgave HS.13: Sudoko
* Opgave HS.14: Højde- og vægtdata
* Opgave HS.15: Gæt på punktplot
* Opgave 5.8: Opløsningsmidler
* Opgave 5.10: Priser på landbrugsejendomme. I spørgsmål 3 behøver du ikke beregne KI.


#### Øvelser onsdag kl. 11:00-11:45 og kl. 13.00-14.45 (se lokaleplanen)

Der er opgaver i mange modeltyper. Brug gerne modeldiagrammet i hver opgave til at gennemskue hvilket set-up der er det relevante.

* Opgave 6.1: Drægtighed for heste. Du skal lave dette "manuelt", altså ved at bruge formler i bogen.
* Opgave HS.16: Parret vs uparret
* Opgave HS.17: Hjerte- og kropsvægt for katte.
* Opgave 6.6: Soyabønner
* Opgave 6.2: Maveeksperiment


***


## Kursusuge 4 {#uge4}

### Generel info

* Jeg har stillet en [frivillig opgave til aflevering](#aflevering1) onsdag den 2. oktober (ved øvelserne). Det er et rasende godt tilbud, men det er frivilligt. Man vil ikke kunne få hjælp til opgaven ved øvelsestimerne (min beslutning, ikke instruktorernes). Brug diskussionforum på Absalon hvis du har spørgsmål.

* Der var meget nyt pensum og mange opgaver i kursusuge 3. Jeg har derfor prøvet at skrue lidt ned for programmet ved øvelserne i kursusuge 4.

* Husk at jeg lægger quizzer ud hver uge, og at der kommer lignende spørgsmål til eksamen. Der ligger nu 3 quizzer i Absalon som trækker på det gennemgåede stof fra kursusugerne 1-3.

* I bliver tit bedt om at *fitte en model*. Det betyder blot at køre den relevante `lm`-kommando. Intet andet. Det betyder fx ikke at man skal tegne noget. Senere i opgaven bliver I altid spurgt om ting, hvor I skal bruge modellen, fx. noget som kan aflæses af summary fra modellen.

* Når du har fittet en model, så lav et `summary` af modellen, og overvej om den indeholder de parameterlinjer som du forventer. Husk også at estimater, p-værdier mm. er uinteressante, hvis man ikke ved hvad de betyder. Det hele er ret ligegyldigt hvis vi ikke kan fortolke parametre og hypoteser, så tænk altid over fortolkningerne når du løser opgaver.

* Der kommer nogle opgaver på onsdag hvor det bliver relevant at transformere data. Kig gerne på analysen fra onsdag eftermiddag i kursusuge 2 og 3 (gæt på punktplot) for eksempler på hvordan man fortolker resultaterne hvis analysen er foretaget på log-transformerede data.

### Forelæsninger

#### Forelæsninger mandag kl 13.00-14.45 i aud - A2-82.01 (3-02)

* Repetition: t-test for relevante hypoteser i lineær regression og ensidet ANOVA
* Afsnit 6.3 - 6.4 om F-test. Jeg vil lægge mindre vægt på LSD-diskussionen end der er lagt op til bogen.
* Afsnit 6.5 om fejltyper ved statistiske test
* Afrunding af kapitel 5 og 6

Slides til dagens forelæsning: [fuld version](slides/sd1_forel190923_handout.pdf) - [kort version: 4 slides per side](slides/sd1_forel190923_short.pdf)

R-program fra forelæsning d. 23/9-2019: [output](R/forel190923_Rprog.html) - [R Markdown](R/forel190923_Rprog.Rmd)

#### Forelæsninger onsdag kl. 9.00-10.45 i aud - A2-82.01 (3-02) og kl. 15.00-15.45 i aud - A2-82.01 (3-02)

* Kapitel 7 om modelkontrol og prædiktion

Slides til dagens forelæsning: [fuld version](slides/sd1_forel190925_handout.pdf) - [kort version: 4 slides per side](slides/sd1_forel190925_short.pdf)

R-program fra forelæsning d. 25/9-2019: [output](R/forel190925_Rprog.html) - [R Markdown](R/forel190925_Rprog.Rmd)

### Øvelsestimer

#### Øvelser mandag kl. 15.00-16.45 (se lokaleplanen)

HS-opgaver kan findes [her](https://github.com/anderstolver/StatData1_2019/tree/master/docs/opgaver). De øvrige opgaver er fra lærebogen.

* Opgave 6.7. Ensidet ANOVA med 4 grupper. 
    - Vink til spg. 1: Når du skal specificere en model, skal du sige hvilken slags model der er tale om og angive antagelserne. 
    - Vink til spg. 2: Du kan fx skifte referencegruppe når du skal sammenligne gruppe 2 og 3
* Opgave 6.14. 
    - Vink til spg 5: Husk at der er lige mange observationer i hver gruppe. Hvad betyder det om SE for de forskellige parvise forskelle? Se evt. afsnit 6.3.2 i lærebogen.
    - Vink til spg. 6: Gennemsnitsværdien for hver *supplier* skal estimeres ved gennemsnittet af n (ukendt!) observationer fra den nye undersøgelse/stikprøve. Find formlen for 95 % - konfidensintervaller for en stikprøve (one sample) og start med at finde ud af, hvilke størrelser som indgår i formlen.
* Opgave HS.19. Specialtilfælde af lineær regression. Data findes på kursushjemmesiden.


#### Øvelser onsdag kl. 11:00-11:45 og kl. 13.00-14.45 (se lokaleplanen)

* Opgave 7.7. Bemærk: Figuren nederst til højre er lidt atypisk i forhold til hvad man ser i praksis, men overvej alligevel hvad "der er galt" med figuren.
* Opgave 7.2. To ekstra spørgsmål: 
    - (5) Bestem et 95% konfidensinterval og et 95% prædiktionsinterval svarende til værdien 8 for radioact. Hvad er fortolkningen af de to intervaller? 
    - (6) For hvilken værdi af radioact  vil man forvente at få en tumorvægt på 0.2?
* Opgave 7.4
<!--
* Opgave HS.20.
-->


### Frivillig afleveringsopgave til onsdag d. 2. oktober {#aflevering1}

Det er frivilligt at aflevere opgaven, men det er god eksamenstræning og en mulighed for at få feedback på jeres måde at formulere jer på. Bemærk at instruktorerne - efter min "ordre" - ikke hjælper med afleveringsopgaven i øvelsestimerne. Hvis du har spørgsmål, så brug diskussionsforum i Absalon, som jeg (=Anders) vil checke ca. dagligt (i hverdage). 

Bemærk, at der kan være ting fra undervisningen i kursusuge 4, som skal bruges til løsning af opgaverne, men de fleste ting burde kunne laves allerede nu.

* Opgave HS.18
* November 2017, opgave 1, men kun spørgsmål 1 og 2 (Data til opgaven findes under linket [Data](data.html) øverst på kursushjemmesiden).

***


## Kursusuge 5 {#uge5}

### Generel info

* Husk [afleveringsopgaven](#aflevering1) (HS.18, Nov 2017 opgave 1 spørgsmål 1+2) der kan afleveres onsdag den 2. oktober ved øvelsernes. Opgaven bedes afleveret senest kl. 11:45. Hvis I laver opgaven i grupper, så nøjes med at aflevere et eksemplar. **Uanset hvad jeg har sagt tidligere, så har instruktorerne ønsket, at I afleverer opgaver på papir. I må naturligvis godt lave besvarelsen eleketronisk (fx. i R Markdown), men opgaven bedes skrevet ud!**

<!--
* NB: Ændret søndag den 30/9: Bemærk at der er en række gennemregnede eksempler i kapitel 14. Kapitlet er ikke pensum, men eksemplerne kan givetvis være gode at få forstand af. Foreløbig er kun afsnit 14.1 relevant, og vi bruger det ved forelæsningerne mandag.
-->

* Nogle af jer efterlyser formler. Jeg vil godt understrege at I har brug for meget, meget få formler fordi vi lader R gøre arbejdet for os, men der er faktisk en formelsamling i Appendix A. Men som sagt: Det er stort set kun i tilfældet med en enkelt stikprøve at I har brug for dem.

* Der er nu også stillet en frivillig [afleveringsopgave til onsdag d. 9. oktober](#aflevering2). Opgaven kræver bl.a. kendskab til stof som gennemgås ved forelæsningen d. 2. oktober.

* Data til gamle eksamensopgaver: Eksamensopgaver fra Januar 2017 og tidligere indeholder R-kode og R-output, men det vil som bekendt sjældent være tilfældet ved den kommende eksamen (der er dog undtagelser). I de kommende uger stiller jeg en del eksamensopgaver, hvor jeg som udgangspunkt lægger data på kursushjemmesiden, og jeg vil kraftigt opfordre jer til at køre analyserne selv. Nogle spørgsmål bliver i øvrigt væsentligt nemmere på den måde!

* Via kursushjemmesiden har du adgang til gamle eksamensopgaver helt tilbage til 2012. Men husk at eksamenformen er ændret løbende, således at nogle opgaver kræver at du selv kører R. Det betyder at opgaverne til og med feb 2017 ikke er helt repræsentative for nye sæt, men problemstillinger og spørgsmål vil være af samme type.

### Forelæsninger

#### Forelæsninger mandag kl 13.00-14.45 i aud - A2-82.01 (3-02)

Der er ikke noget nyt-nyt stof i dag indholdsmæssigt. I stedet samler vi op på hængepartier og laver lidt repetition.

Slides til dagens forelæsning: [fuld version](slides/sd1_forel190930_handout.pdf) - [kort version: 4 slides per side](slides/sd1_forel190930_short.pdf)

R-program fra forelæsning d. 30/9-2019: [output](R/forel190930_Rprog.html) - [R Markdown](R/forel190930_Rprog.Rmd)

#### Forelæsninger onsdag kl. 9.00-10.45 i aud - A2-82.01 (3-02) og kl. 15.00-15.45 i aud - A2-82.01 (3-02)

* Afsnit 8.1 om multipel regression

Slides til dagens forelæsning: [fuld version](slides/sd1_forel191002_handout.pdf) - [kort version: 4 slides per side](slides/sd1_forel191002_short.pdf)

R-program fra forelæsning d. 2/10-2019: [output](R/forel191002_Rprog.html) - [R Markdown](R/forel191002_Rprog.Rmd)


### Øvelsestimer

#### Øvelser mandag kl. 15.00-16.45 (se lokaleplanen)

* November 2017, opgave 2. Der er ikke data til denne opgave. I anden halvdel af delspørgsmål 3 er det nok at bestemme den faktor som regnmængden forøges med (snarere end den procentvise forøgelse); dette gælder både estimat og konfidensinterval.

* Opgave HS.22: Lineær regression og ensidet ANOVA på samme datasæt. Forskel på at inddrage en forklarende variabel som kontinuert variabel og som kategorisk variabel (faktor).

* Opgave HS.21: Test af sammensatte hypoteser i ensidet ANOVA. 

#### Øvelser onsdag kl. 11:00-11:45 og kl. 13.00-14.45 (se lokaleplanen)


HS-opgaver kan findes [her](https://github.com/anderstolver/StatData1_2019/tree/master/docs/opgaver). De øvrige opgaver er fra lærebogen.

* Januar 2018, opgave 2. Datasættet findes allerede på kursushjemesiden under linket [Data](data.html) i forbindelse med Opgave HS.9.

* November 2018, opgave 2.

<!--
* November 2016, opgave 2. Data ligger i filerne aske-kalk.xlsx og aske-kalk.txt, så kør hellere analysen selv. Kommentar til (b): Brug predict-funktionen i stedet for opgavens beregningshjælp. Kommentar til (d) og (f): Disse to spørgsmål er svære, så fortvivl ikke hvis du ikke umiddelbart kan løse dem.
  
* HS.23: To stikprøver med og uden ens spredning.
-->

* Opgave 7.8: Minder en del om Opgave HS. 22 fra mandagsøvelserne.

### Frivillig afleveringsopgave til onsdag d. 9. oktober {#aflevering2}

Det er frivilligt at aflevere opgaven, men det er god eksamenstræning og en mulighed for at få feedback på jeres måde at formulere jer på. Bemærk at instruktorerne - efter min "ordre" - ikke hjælper med afleveringsopgaven i øvelsestimerne. Hvis du har spørgsmål, så brug diskussionsforum i Absalon, som jeg (=Anders) vil checke ca. dagligt (i hverdage). 

* Januar 2019, opgave 2 (Data til opgaven findes under linket [Data](data.html) øverst på kursushjemmesiden)


***


## Kursusuge 6 {#uge6}

### Generel info

* Husk [afleveringsopgaven](#aflevering2) (Januar 2019, opgave 2) der kan afleveres onsdag den 9. oktober ved øvelsernes. Opgaven bedes afleveret senest kl. 11:45. Hvis I laver opgaven i grupper, så nøjes med at aflevere et eksemplar. Det er instruktorernes ønske, at I afleverer opgaver på papir. I må naturligvis godt lave besvarelsen eleketronisk (fx. i R Markdown), men opgaven bedes skrevet ud!

* Jeg har nu stillet en frivillig [afleveringsopgave](#aflevering3) til aflevering i kursusuge 7. For at sikre, at I kan nå at få rettet opgaverne, så bliver afleveringsfristen mandag d. 21/10 (efter undervisningspausen i uge 42).

* I denne uge gør vi normalfordelingsmodellerne færdige!

* Husk som altid at lave de opgaver, du ikke når i timerne, derhjemme.

* De fleste af HS-opgaverne ligner de kommende eksamensopgaver lige så meget som de gamle eksamensopgaver.

* Husk at der ligger data til de fleste gamle eksamensopgaver. Kør selv analyserne!

### Forelæsninger

#### Forelæsninger mandag kl 13.00-14.45 i aud - A2-82.01 (3-02)

Forelæsningen bører følgende afsnit i lærebogen

* Afsnit 8.2 (s. 224-234) om den additive moel for tosidet variansanalyse (ANOVA)
+ 8.4.1-8.4.2 (s. 243-249) om den tosidede variansanalysemodel med vekselvirkning

Slides til dagens forelæsning: [fuld version](slides/sd1_forel191007_handout.pdf) - [kort version: 4 slides per side](slides/sd1_forel191007_short.pdf)

R-program fra forelæsning d. 7/10-2019: [output](R/forel191007_Rprog.html) - [R Markdown](R/forel191007_Rprog.Rmd)


#### Forelæsninger onsdag kl. 9.00-10.45 i aud - A2-82.01 (3-02) og kl. 15.00-15.45 i aud - A2-82.01 (3-02)

* Eventuelle hængepartier vedrørende tosidet ANOVA
* Modeller med både kvantitative og kontinuerte forklarende variable: afsnit 8.3 (side 234-242)
* Om eftermiddagen: gennemgang af Quiz 6 og eventuelle hængepartier

Slides til dagens forelæsning: [fuld version](slides/sd1_forel191009_handout.pdf) - [kort version: 4 slides per side](slides/sd1_forel191009_short.pdf)

R-program fra forelæsning d. 9/10-2019: [output](R/forel191009_Rprog.html) - [R Markdown](R/forel191009_Rprog.Rmd)

### Øvelsestimer

#### Øvelser mandag kl. 15.00-16.45 (se lokaleplanen)

* November 2017, opgave 3. Vink til spørgsmål 2: Husk hvad vekselvirkning betyder. 

<!--
* Opgave HS.24
-->

* Januar 2015, opgave 1. Data ligger på kursushjemmesiden ( [Data](data.html) ) som happy.txt og happy.xlsx. Derfor må du gerne selv regne på data i R, og fx. bruge R til at besvare delopgaverne (b) og (c) i stedet for at sætte tal fra den viste R udskrift ind i formlerne i bogen. Ekstra spørgsmål (e): Bestem et 95% prædiktionsinterval svarende til selvskab=25, indkomst=35 og VAT=18, og forklar hvordan intervallet skal fortolkes.

* Opgave 8.2, men erstat spørgsmålene med følgende: Brug en tosidet ANOVA uden vekselvirkning til at undersøge om der er en effekt af sort (variety) og gødningsmængde (fertilizer) på udbyttet.


#### Øvelser onsdag kl. 11:00-11:45 og kl. 13.00-14.45 (se lokaleplanen)

<!--
* Quiz 6: Start på quizzen cirka 15.15, så du har en halv times tid. Hvis du bliver hurtigt færdig, så kan du gå tilbage til opgaverne. Vi snakker den igennem ved den efterfølgende forelæsning.
-->

* Opgave HS.25: Tosidet ANOVA. Data til opgaven findes under Opgave HS.25 på [siden med data](data.html).

* Opgave HS.26: Model med både kategorisk og kontinuert forklarende variable.
* Opgave HS.27: Det kan være en fordel at se på slide 33 (og evt. 29-32) fra forelæsningen d. 23/9-2019 som er nyttige, men ikke har været diskuteret i detaljer.
* Opgave 8.9. Dette er en fortsættelse af opgave 6.6 som I regnede i kursusuge 3. 


### Frivillig afleveringsopgave til mandag d. 21. oktober {#aflevering3}

Det er frivilligt at aflevere opgaven, men det er god eksamenstræning og en mulighed for at få feedback på jeres måde at formulere jer på. Bemærk at instruktorerne - efter min "ordre" - ikke hjælper med afleveringsopgaven i øvelsestimerne. Hvis du har spørgsmål, så brug diskussionsforum i Absalon, som jeg (=Anders) vil checke ca. dagligt (i hverdage). 

* Januar 2019, opgave 1 (Data til opgaven findes under linket [Data](data.html) øverst på kursushjemmesiden)


***


## Kursusuge 7 {#uge7}

### Generel info

* Husk [afleveringsopgaven](#aflevering3) (Januar 2019, opgave 1) der kan afleveres mandag den 21. oktober ved øvelserne. Opgaven bedes afleveret senest kl. 16:45. Hvis I laver opgaven i grupper, så nøjes med at aflevere et eksemplar. Det er instruktorernes ønske, at I afleverer opgaver på papir. I må naturligvis godt lave besvarelsen eleketronisk (fx. i R Markdown), men opgaven bedes skrevet ud!

* Jeg har nu lagt [vejledende besvarelser](https://github.com/anderstolver/StatData1_2019/tree/master/docs/eksamensopgaver) ud til nogle af de gamle eksamenssæt. Jeg tilbageholder besvarelserne for eksamenssættene fra januar 2018 og januar 2019, for jeg har tænkt mig at bruge opgaver fra disse eksamenssæt ved undervisningen i kursusugerne 7 og 8. Bemærk dog at instruktorerne har lagt vejledende besvarelser ud (i Absalon) til de eksamensopgaver fra jan 2018+2019, som har været på programmet ved øvelsestimerne i kursusuge 1-6. 

### Forelæsninger

#### Forelæsninger mandag kl 13.00-14.45 i aud - A2-82.01 (3-02)

* Kapitel 11: om binomialfordelingen

Slides til dagens forelæsning: [fuld version](slides/sd1_forel191021_handout.pdf) - [kort version: 4 slides per side](slides/sd1_forel191021_short.pdf)

R-program fra forelæsning d. 21/10-2019: [output](R/forel191021_Rprog.html) - [R Markdown](R/forel191021_Rprog.Rmd)

#### Forelæsninger onsdag kl. 9.00-10.45 i aud - A2-82.01 (3-02) og kl. 15.00-15.45 i aud - A2-82.01 (3-02)

* Kapitel 12, dog ikke afsnit 12.2.3 og 12.2.4 som ikke er pensum

Slides til dagens forelæsning: [fuld version](slides/sd1_forel191023_handout.pdf) - [kort version: 4 slides per side](slides/sd1_forel191023_short.pdf)

R-program fra dagens forelæsning: [output](R/forel191023_Rprog.html) - [R Markdown](R/forel191023_Rprog.Rmd)

### Øvelsestimer

#### Øvelser mandag kl. 15.00-16.45 (se lokaleplanen)

Du bør sikre dig, at du bruger nok tid på kurset i de sidste uger - særligt med henblik på at få træning i at regne opgaver. Du kan ikke regne med, at du kan nå at lave alle opgaverne i øvelsestimerne, så regn med at du skal bruge tid hjemme, hvis du vil nå igennem alle opgaver.


* Opgave 11.1: beregning af sandsynligheder for udvalgte hændelser i en binomialfordeling

* Opgave HS.28: estimation, konfidensintervaller og hypotesetest for en binomialfordeling

* Opgave HS.29: sammenligning af forskelle mellem to binomialfordelinger (*differences between proportions*)

* November 2018, opgave 1: god opgave til repetition af ensidet ANOVA.

* Opgave 11.4. Kommentar til spørgsmål 2: Du kan bruge binom.test, så du behøver ikke bruge normalfordelingsapproksimationen som der ellers lægges op til i vinket (**Opgaverne 11.4 og HS.28 minder en del om hinanden!**)

#### Øvelser onsdag kl. 11:00-11:45 og kl. 13.00-14.45 (se lokaleplanen)

Du bør sikre dig, at du bruger nok tid på kurset i de sidste uger - særligt med henblik på at få træning i at regne opgaver. Du kan ikke regne med, at du kan nå at lave alle opgaverne i øvelsestimerne, så regn med at du skal bruge tid hjemme, hvis du vil nå igennem alle opgaver.

* Quiz 7: Start på quizzen cirka 14.15, så du har en halv times tid. Hvis du bliver hurtigt færdig, så kan du gå tilbage til opgaverne. Vi snakker den igennem ved forelæsningen onsdag eftermiddag.
* Opgave HS.30: test for uafhængighed
* Opgave 12.5: tosidede antalstabeller (3 x 3 tabel)
* Opgave HS.32: se bort for spørgsmål (e).
* Januar 2018, opgave 1: opgave der kommer godt rundt i pensum!

***


## Kursusuge 8 

### Generel info

### Forelæsninger

#### Forelæsninger mandag kl 13.00-14.45 i aud - A2-82.01 (3-02)

### Øvelsestimer

#### Øvelser mandag kl. 15.00-16.45 (se lokaleplanen)

<!--
* (November 2017, opgave 4, men kun spørgsmål 1)
* (November 2015, opgave 1. Data ligger som mazdas.txt og mazdas.xlsx på Absalon)
* Brug desuden timerne til at stille spørgsmål til opgaver fra kurset. 
-->

