---
title: "Oversigt over R materiale"
output: 
  html_document:
    toc: true
---

***

# Installation, R pakker og nyttige links

## Installation af R og R Studio

Du skal først installere R: [www.r-project.org/](http://www.r-project.org/) 

* klik CRAN i venstre bjælke og vælg et mirror i Danmark
* vælg operativsystem
* følg vejledningen (brug defaultindstillingerne)

Dernæst skal du installere RStudio: [www.rstudio.com](http://www.rstudio.com/)

* Vælg "RStudio Desktop" (gratis)

Hvis du allerede har RStudio installeret, så kan programmet også updateres inde fra RStudio 

* vælg `Help` i menuen og derefter `Check for updates`


***


## R pakker benyttet på Statistisk Dataanalyse 2

R kode er organiseret i R pakker. Når man installerer R på sin computer får man adgang til en lang række R funktioner, men det er ikke alle R funktioner der er tilgængelige, blot man åbner R. Derfor vil man ofte på brug for at *loade* R pakker i sine R programmer. 

R pakken `MASS` følger med R standardinstallationen, men skal loades i dine R programmer ved at køre kommandoen 
```{r}
library(MASS)
```

Følgende øvrige R pakker har været benyttet / omtalt på Statistisk Dataanalyse 1 (2019/2020) og disse R pakker skal du selv først installere på din computer og dernæst loade ved at køre kommandoen `library("pakkenavn")`.

* `isdals`: indeholder datasæt fra lærebogen
* `ggplot2`: indeholder funktioner til at lave figurer
* `tidyverse`: indeholder en masse nyttige funktioner til at lave manipulationer med datasæt
* `readxl`: indeholder bl.a funktionen `read_excel` til indlæsning af excel-filer

Du kan bl.a. løse [Opgave HS. 2](opgaver/hs1-4.pdf) for at lære, hvordan du kan downloade en R pakke.


***


## Vejledninger og notater

Her findes en liste over nogle nyttige/links til vejledninger og manualer, som kan være nyttige, når man arbejder med R. 

Nogle af vejledningerne er skrevet på et forholdsvis højt niveau, så man skal ofte have noget erfaring med R, for at forstå det hele.

* Anders Tolver: [Notat om at lave grafik i R](R/grafik_i_R.html)

* Anders Tolver: [Notat om at arbejde med R Markdown formatet](R/RMarkdown.html) (skrevet til StatData1)

* Anders Tolver: [Notat om datasæt indsamlet ved forelæsning d. 2/9-2019](R/working_with_data.html)


<!--
* **Helle Sørensen:Gammels notat om R:** skrevet med henblik på studerende
-->

* Hadley Wickham & Garrett Grolemund: [R for Data Science](https://r4ds.had.co.nz): virkelig velskrevet bog med fokus på værktøjerne fra R pakkerne i `tidyverse` (for den øvede R bruger)

* Yihui Xie, J. J. Allaire & Garrett Grolemund [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/): hvis du bliver glad for at arbejde i R Markdown formatet, så findes der mange gode råd i denne bog (for den øvede R bruger)

***


# Centrale R begreber fra undervisningen

## Uge 1

* Ved undervisningen i uge 1 talte vi bl.a. om R kommandoerne
    - `mean, sd, var, median, summary`: til at beskrive en numerisk/kontinuert/kvantitativ variabel
    - `plot, boxplot, hist`: til visualisering af data
    - `table`: til tabellering af kategoriske variable
    - `lm`: til at estimere en regressionslinje og beregne gruppegennemsnit i ensidet variansanalyse
    - `abline`: til at tilføje en linje til et scatterplot
    - `cor`: til at beregne en korrelationskoefficient mellem to kvantitative kontinuerte variable
* R-program fra forelæsning d. 2/9-2019: [output](R/forel190902_Rprog.html) - [R Markdown](R/forel190902_Rprog.Rmd)
* R-program fra forelæsning d. 4/9-2019: [output](R/forel190904_Rprog.html) - [R Markdown](R/forel190904_Rprog.Rmd)
    
<!--

    - hvordan man installerer og loader en R pakke
    - hvordan man kommer i gang med at bruge R markdown formatet
-->

## Uge 2

* Ved undervisningen i uge 2 talte vi bl.a. om R kommandoerne
    - `pnorm`: til beregning af sandsynligheder i en normalfordeling
    - `qnorm`: til beregning af fraktiler i en normalfordeling
    - `rnorm`: til simulation (dvs. trækning af kunstige data) fra en normalfordeling
    - `qqnorm`: til at tegne et QQ-plot med henblik på at vurdere om data ligner en normalfordling
    - `read_excel`, `read.table`: til indlæsning af data fra excel-filer (.xlsx) og tekst-filer (.txt)
    - `qt`: til beregning af fraktiler i en t-fordeing (bruges i forb. med konfidensintervaller)
    - `t.test, confint`: til beregning af konfidensintervaller for gennemsnit baseret på en enkelt stikprøve

* R-program fra forelæsning d. 9/9-2019: [output](R/forel190909_Rprog.html) - [R Markdown](R/forel190909_Rprog.Rmd)
* R-program fra forelæsning d. 11/9-2019: [output](R/forel190911_Rprog.html) - [R Markdown](R/forel190911_Rprog.Rmd)

## Uge 3

* Ved undervisningen i uge 3 talte vi bl.a. om R kommandoerne
    - `group_by()`: til at fortage beregning af stikprøvestørrelser for en kontinuert variabel separat for målinger i hver gruppe givet ved en kategorisk variabel
    - `lm`: til at estimere parametre i en ensidet variansanalysemodel (ANOVA)
    - `lm`: fokus på betydning af forskellen mellem formelsyntaksen `org ~ type - 1` og `org ~ type`
    - `relevel`: til at ændre referencegruppen i forbindelse med estimation i ensidet ANOVA
    - `confint`: til beregning af konfidensintervaller i en ensidet ANOVA
    - `t.test`: til sammenligning af to stikprøver (både parrede og uparrede)
    - `pt`: benyttet til beregning af P-værdi ud fra en (manuelt beregnet) t-teststørrelse (ofte foretages denne beregning automatisk og angives i R outputtet)
    
  
* R-program fra forelæsning d. 16/9-2019: [output](R/forel190916_Rprog.html) - [R Markdown](R/forel190916_Rprog.Rmd)

* R-program fra morgenforelæsning d. 18/9-2019: [output](R/forel190918_Rprog.html) - [R Markdown](R/forel190918_Rprog.Rmd)

* R-program fra eftermiddagsforelæsning d. 18/9-2019: [output](R/punktplot190918_Rprog.html) - [R Markdown](R/punktplot190918_Rprog.Rmd)

## Uge 4

* Ved undervisningen i uge 4 talte vi bl.a. om R kommandoerne
    - `drop1()`: til at udtrække F-test for sammenligning af (flere end tre) gruppemiddelværdier i en ensidet ANOVA
    - `anova(nullModel, fullModel)`: til at sammenligne (dvs. lave F-test) en fuld model og en nulmodel (med restriktioner på nogle af parametrene)
    - `res(), rstandard()`: til at udtrække residualer og standardiserede residualer fra en model fittet med `lm()`
    - `qqnorm`: til at tegne et QQ-plot med henblik på at vurdere om de standardiserede residualer ligner en standardnormalfordeling (middelværdi 0 og varians 1)
    - `predict()`: til at lave prædiktionsintervaller
    

* R-program fra forelæsning d. 23/9-2019: [output](R/forel190923_Rprog.html) - [R Markdown](R/forel190923_Rprog.Rmd)

* R-program fra forelæsning d. 25/9-2019: [output](R/forel190925_Rprog.html) - [R Markdown](R/forel190925_Rprog.Rmd)

## Uge 5

* Ved undervisningen i uge 5 talte vi bl.a. om R kommandoerne
    - `lm(freq ~ temp + I(temp^2), data=eels)`: til at fitte en kvadratisk regressionsmodel
    - `anova()`: til at teste en lineær regressionsmodel imod hhv. en kvadratisk regressionsmodel og imod en ensidet ANOVA
    - `lm(Volume ~ Height + Girth)`: til at fitte en multipel lineær regressionsmodel

* R-program fra forelæsning d. 30/9-2019: [output](R/forel190930_Rprog.html) - [R Markdown](R/forel190930_Rprog.Rmd)

* R-program fra forelæsning d. 2/10-2019: [output](R/forel191002_Rprog.html) - [R Markdown](R/forel191002_Rprog.Rmd)

## Uge 6

* Ved undervisningen i uge 6 talte vi bl.a. om R kommandoerne
    - `interaction.plot()`: laver et vekselvirkningsplot til at undersøge effekten af to kategoriske variable i forbindelse med tosidet ANOVA
    - `lm(hojde ~ studie + kon + studie*kon)`: til at fitte en tosidet ANOVA med vekselvirkning
    - `lm(hojde ~ studie + kon)`: til at fitte en tosidet ANOVA uden vekselvirkning
    - `lm(time ~ day + women`): til at fitte en *blandet model* (både kontinuert og kategoriske forklarende variable)
    
* R-program fra forelæsning d. 7/10-2019: [output](R/forel191007_Rprog.html) - [R Markdown](R/forel191007_Rprog.Rmd)

* R-program fra forelæsning d. 9/10-2019: [output](R/forel191009_Rprog.html) - [R Markdown](R/forel191009_Rprog.Rmd)

## Uge 7

* Ved undervisningen i uge 7 talte vi bl.a. om R kommandoerne
    - `dbinom(), pbinom()`: til beregning af sandsynligheder for en binomialfordelt variabel Y
    - `prop.test()`: til beregning af *forbedret* konfidensinterval for sandsynlighedsparameteren p i en binomialfordeling
    - `binom.test()`: til at teste en hypotese $H_0: p = p_0$ om parameteren i en binomialfordeling
    - `prop.test()`: til beregning af konfidensinterval for forskellen mellem sandsynligheder i to binomialfordelinger (eng: *differences between proportions*)
    
* R-program fra forelæsning d. 21/10-2019: [output](R/forel191021_Rprog.html) - [R Markdown](R/forel191021_Rprog.Rmd)
